### PR TITLE
Build script to use Maven

### LINKED ISSUE #152: Use public jars for building
For auditing and security purposes, it would be good to know the origin and current security status of the libraries listed in the `lib` folder. This would be easier to automate if the build would use Maven or Gradle for dependency resolution, since then there are standard security scanners like dependabot or Snyk.io to verify the current dependency status.

Dependencies that are not available via standard Maven repositories like Maven Central or JCenter could still be listed in this directory and referenced directly.

### PR DESCRIPTION
**Pull request by blootsvoets**
Use Maven to build this repository. Fixes #152.
- [x] compile sources
- [x] locate dependencies
- [x] build distributable packages
- [x] update README information
- [x] test packages
  - [x] test on macOS
  - [x] test on Windows
  - [x] test on Linux

In order to have "one artifact per module" philosophy of Maven, the source is split up into three submodules. A base source, a RabbitInAHat-specific source and a WhiteRabbit-specific source.

This build creates shell scripts instead of a runnable jar. Teradata dependencies were not available on Maven Central and have been added as a local indexed Maven repository.

### CODE REVIEW

**Comment by blootsvoets** [comment]
@MaximMoinat @schuemie could you please take a look?  If a runnable jar remains the preferred method, I can try to change the build.

**Comment by schuemie** [comment]
I'm a bit of a Maven noob, so please forgive me if I say stupid things. First of all, this looks great! I can run the build fine on Windows, and execute both programs.

I don't have a preference for runnable jars, but then I don't know whether this approach is likelier to cause or prevent issues for users to get it running. Lets  keep it like you have.

I do have two questions:

1. Would it be possible to put the .bat and .sh files in the root instead? Having people navigate to a bin folder might be confusing.

2. On my build the shell scripts don't have a .sh extension. Is that an issue? (I don't have a Mac). It is at least is an inconsistency with the new instructions in the README.

**Comment by blootsvoets** [comment]
Thanks for the review.

1. I'll have a look. I'm not sure because the directory structure is determined by another plugin.
2. thanks for noticing, I'll change that.

**Comment by schuemie** [comment]
Thanks! This is great work.

**Pull request merged**
