### PR TITLE
Google BigQuery integration

### PR DESCRIPTION
**Pull request by mgkahn**
First **ever** pull request so bear with me if I do this wrong.

Branch bigquery contains changes needed to run on BQ data sets. Lots of little changes but most are in DBConnector (JDBC code) and  SourceDataScan (GBQ-specific SQL syntax).

Other changes:
- created folder /lib/bigquery_jars/ for the 52(!!) JDBC-related files from Google/Simba
- included PDF documentation in /lib/bigquery_jars/
- created bash script in /lib to move the 16 jar files that seemed to be required into the local repo
- added these 16 dependencies to rabbit-core/pom.xml

What I know I need help doing:
- how do I alter the documentation to include information about the BQ JDBC authentication? Specifically, I enabled two different authentication methods -- authenticating via service account and authenticating via user application default. This needs to be explained in the user documentation.
- what else do I need to do to be a good OHSDI code contributor?

### CODE REVIEW

**Comment by MaximMoinat** [comment]
Hi Michael, thanks for opening this. Additional connections are very welcome. I have asked Martijn and my colleague Joris for a review.

One request, the dependencies are now bundled using Maven. See the [pom.xml](https://github.com/OHDSI/WhiteRabbit/blob/master/pom.xml). The lib folder for teradata should not have bene there. Could you try adding the jar dependencies to the pom.xml? See the [development section of the readme](https://github.com/OHDSI/WhiteRabbit#development ) on basis maven use.

**Comment by mgkahn** [comment]
Not sure I am following your requests:
- The dependencies for the BigQuery JDBC jars have been added to rabbit-core/pom.xml
- I dumped all of the Simba BigQuery jars into /lib just to include them. They are not referenced in the pom.xml dependencies. I was following what was done for the lib/teradata jar files. If I am reading your posting lib/teradata was a mistake so lib/bigquery is probably equally a mistake. It can be removed w/o any issues. The necessary BigQuery jars have been added to the local maven directory and the pom.xml file references only the local maven directory.

Am I addressing your concerns? If so, just cleave off lib/bigquery (and lib/teradata). Maven will build correctly w/o these directories.

**Comment by MaximMoinat** [comment]
Just been told that jars of unpublished dependencies indeed might need to be added separately to the lib. This is the case for the Teradata driver and might be the case for the Simba jars you provided. That being said, the more can be included via Maven only, the better.

Could you verify whether the BigQuery integration still works without the jars in the lib folder? (if you haven't already)

**Comment by mgkahn** [comment]
Well, I can most certainly confirm that WR builds and executes correctly without the /lib dir for Google BigQuery (probably because I deployed the necessary GBQ jars into the local repo and added the dependencies to rabbit-core/pom.xml). In cleaving off /lib, I did remove the terra data jars but I have no way of testing if this has broken terradata execution. It doesn't bomb on building and executing for BigQuery. Three approaches:

- -Ask somebody with access to terra data to try to executable that has been built in the big query branch (created w/o /lib) to see if it works,  or
-- I can put /lib and just the terradata jars back into the branch, or
-- Even though not needed to build/run WR, I could go back to including the google jars .lib  as before.  The current maven repo only includes/uses a small subset of the 50+ jars that Simba distributes for BQ. I included the full set of google jars /lib just so they were available in case we find later that there is an additional jar that has to be deployed into the local maven repo for some new functionality. By including the complete set of jars that I am using, everything would be at the same release version. 

LMK your preference. At this moment, I pushed to my repo a version without /lib that built and tested successfully against GBQ.

**Comment by MaximMoinat** [comment]
Great! I think option 2 would be best, just not to break existing integrations. There is a separate discussion on where to publish the teradata.jar (#156).

We are also considering a rewrite of the database connections, such that we can use the regular BigQuery api instead of the Simba JDBC. This might be something for the future and we are eager to support BigQuery, so we might merge your implementation first. Will keep you updated.

**Comment by mgkahn** [comment]
OK. /lib with terradata jars only pushed to my repo (Option #2). Do you need me to send a new PR request that points to this commit or does the original PR always point to the latest commit? (PRs are new to me so my grasp of these details is thin).

**Comment by MaximMoinat** [comment]
This is fine, no need to open a new PR. Probably will merge after the symposium (next week). I want to wait for a quick review by @schuemie.

**Comment by MaximMoinat** [comment]
Hi Michael. I have been trying out your BigQuery plugin, but I keep getting that the Simba driver cannot be found. Trying both after and before your removed the jars in ./lib. Also, I have executed the `mvn-deploy-googlejars.sh`. Are there any steps I am missing?

By the way, have you already been able to run a `mvn install` to generate the WR and RiaH executables? That is failing for me namely. Thanks!

**Comment by mgkahn** [comment]
The attached link is a short video (no audio) showing me use Maven to clean -> compile -> install my version of WR without any errors. 

https://drive.google.com/file/d/1n26MDPbMvgHC7k3G_-Xq70NQ-lp3oJnP/view?usp=sharing

By running "mvn-deploy-googlejars.sh", you should have added the necessary Simba jars from /lib into your local maven repository (~/.m2). All of the **needed** Simba jars (not all in /lib are used), should be in ~/.m2/repository/com/simba/googlebigquery/jdbc. Can you check that the "mvn-deploy-googlejars.sh" script successfully entered the jars into your local repo? I would have expected if that didn't happen, mvn-compile would have failed. Can you see if the jars were added to the class path variable in whiterabbit.sh execution script (in dist/bin)? Else I'm stuck why your build doesn't find the jars. 

Later today I will log into a naive machine, download my GitHub repo and see if I have missed a step with a fresh machine. I'm stuck on a webinar for the next 3 hours. Will post here after I try this.

Regarding RiaH, I've not done/tested anything there because I wasn't expecting any dependency on GBQ connectivity in that application. I have been tracking the significant updates in functionality that probably will need GBQ connectivity but I was waiting for things to settle down before inserting GBQ into the new work.

Also, I did NOTHING to include GBQ in the synthetic data generator.

**Comment by mgkahn** [comment]
Just updated bigquery branch in my github fork. We **do** need to include the simba jars in lib/com since they cannot be found in any available public maven repo (or at least I didn't find one that had them). I tried this setup on a fresh machine and `mvn install`  worked fine. LMK if you need more from me.

I know I need to add text to the instructions for GBQ users. Need help with how I do this.

**Comment by MaximMoinat** [comment]
Thanks for the changes. Just tested it again, and the GBQ connection now works for me too. Will merge in develop.

Considering the documentation: the comments you wrote in the DBConnector helped me a lot to use the connection. If you want, please add a section on the GBQ connection on the[ wiki page](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:whiterabbit).
https://github.com/mgkahn/WhiteRabbit/blob/d7494c8b91bc7afa06ed96a9425c433dcbfa0d12/rabbit-core/src/main/java/org/ohdsi/databases/DBConnector.java#L238-L247

**Pull request merged**
