### PR TITLE
Ignore settings/classpath

### PR DESCRIPTION
**Pull request by aguynamedryan**
I was having issues where my .classpath and .settings files/folders were slightly different from those of the OHDSI repo.  These are settings used by Eclipse and seem to be unique to each computer on which Eclipse is run.

I removed .classpath and .settings using git rm -r --cached, meaning that these commits shouldn't delete the files from a user's working directory, but I could be wrong.

### CODE REVIEW

**Comment by schuemie** [comment]
I've shared the .classpath file with other Eclipse developers in the past without problems, so it should be possible. Removing it from Github will mean we'll have to manually sync our classpaths.

Can you tell me what differences in classpath you noticed?

**Comment by aguynamedryan** [comment]
Here's a gist that contains a diff between my classpath and the one in the repo: https://gist.github.com/aguynamedryan/85f89f63290af4bfe7a7

Basically, each of my coworker's has a slightly different value for `<classpathentry kind="con" path="...">`

Each of us had to change the JRE entry because it started off as "unbound" as seen here: 

image

While the JRE is listed as "unbound", almost all references to all classes can't be resolved in Eclipse and it throws up a ton of errors (you can see all the red highlighted lines in the above image).

I'm very rusty on Java/Eclipse so I have no idea why these settings needed adjusting before all our error messages went away.  But once we selected a something like this:

image

All the errors went away, but then our classpath file showed up with uncommitted changes in our working copies.  It's been problematic having this file float around in an uncommitted state because checking out branches sometimes overwrites it and then we end up having to resolve that "unbound" problem again.

If my pull request is a bad way to deal with this, let's trash it, but I'd like to find someway to avoid this "unbound" problem without ending up with the classpath file showing up as uncommitted all the time.

Thanks!

**Comment by schuemie** [comment]
I just changed the .classpath to what I think is what you have. It also works fine on my Eclipse. No idea why Eclipse had added the extra stuff to `JRE_CONTAINER`. 

Can you try the new .classpath to see if it works for you?

**Comment by aguynamedryan** [comment]
@schuemie, your changes seem to work for me and one of my colleagues.  Thanks.

Closing.

**Pull request closed without merging**
