### PR TITLE
Speed up tests on Redshift

### PR DESCRIPTION
**Pull request by arestenko**
Replace separate insert statements with CTAS and a union of values when target DBMS is Redshift. 
Allow user to choose DBMS in the UI.

### CODE REVIEW

**Comment by arestenko** [comment]
Agree on popup.

Data frame is used to group values to be inserted in a table together. With SQL Server you can insert rows in tables in any order, but in Redshift it has to be a single `create table as` statement. Otherwise it's very slow. 

It's used as before to write SQL file, but instead of standard `write` function, `writeSql`  is used:
```
writeSql(insertDf, "insert.sql")
writeSql(testSql, "test.sql")

### Execute tests ###

library(DatabaseConnector)
connectionDetails <- createConnectionDetails(user = "<user name>",
                                             password = "<password>",
                                             dbms = "redshift",
                                             connectionString = "jdbc:redshift://<cluster name>.redshift.amazonaws.com:5439/aaresten_test?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory",
                                             schema = 'public')
connection <- connect(connectionDetails)

f = file('insert.sql', open="r")
sql = readLines(f) 
close(f)
executeSql(connection, paste(sql, collapse = "\n"))
```

**Comment by alondhe** [comment]
@schuemie - the main reason for moving away from 1 single SQL script with inserts is because of the slow performance on MPP systems like Redshift and APS, which ends up meaning we write and execute test cases against an SMP system like SQL Server before ultimately running Builder on an MPP. 

We'd like to run all test cases in the same database platform of the eventual CDM build to ensure database parity in the "test" and "run" phases. Using CTAS's and UNIONs will help ensure we can accomplish this due to the performance gain.

**Comment by schuemie** [comment]
Ok, I now understand what you're trying to do. However, these two lines now really don't make sense to an end user (even less than what we had before):
```r
writeSql(insertDf, "insert.sql")
writeSql(testSql, "test.sql")
```
What if instead we create two functions that spit out the two pieces of SQL after the user is done specifying the tests. So something like:
```r
sql1 <- generateInsertSql()
sql2 <- generateTestSql()
```
Users could then choose to write `sql1` and `sql2` to file (or not), and we no longer require users to be aware of magic variables (insertDf and testSql).

**Comment by arestenko** [comment]
Martijn, sure, `generateInsertSql` added. 
`generateTestSql` is not required because `testSql` global variable is already made available by framework. So instead of 
```
writeSql(insertDf, "insert.sql")
writeSql(testSql, "test.sql")
```
User should now use
```
write(insertSql, "insert.sql")
write(testSql, "test.sql")
```
(exactly as before, e.g. in HcupTest.R example). Or just use variables `insertSql` and `testSql` however they like.

**Pull request merged**
